"""Initial migration with burk data

Revision ID: daa49dc3df43
Revises: 
Create Date: 2025-06-26 21:43:03.009245

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer, Boolean, Float, ForeignKey
import sqlalchemy as sa

from app.services.user.auth import get_password_hash

# revision identifiers, used by Alembic.
revision: str = 'daa49dc3df43'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    admin_password = get_password_hash('admin123')
    user1_password = get_password_hash('password123')  
    user2_password = get_password_hash('test456')

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('password', sa.String(length=300), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transactions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('transaction_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('signature', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )

    users_table = table('users',
        column('id', Integer),
        column('email', String),
        column('password', String),
        column('full_name', String),
        column('is_admin', Boolean)
    )

    accounts_table = table('accounts',
        column('id', Integer),
        column('user_id', Integer),
        column('balance', Float)
    )

    transactions_table = table('transactions',
        column('id', Integer),
        column('transaction_id', String),
        column('user_id', Integer),
        column('account_id', Integer),
        column('amount', Float),
        column('signature', String)
    )

    op.bulk_insert(users_table, [
        {
            'email': 'admin@example.com',
            'password': admin_password,
            'full_name': 'Администратор',
            'is_admin': True
        },
        {
            'email': 'user1@example.com',
            'password': user1_password,
            'full_name': 'Иван Иванов',
            'is_admin': False
        },
        {
            'email': 'user2@example.com',
            'password': user2_password,
            'full_name': 'Петр Петров',
            'is_admin': False
        }
    ])

    op.bulk_insert(accounts_table, [
        {'user_id': 1, 'balance': 10000.0},
        {'user_id': 2, 'balance': 5000.0},
        {'user_id': 3, 'balance': 2500.0}
    ])

    op.bulk_insert(transactions_table, [
        {
            'transaction_id': 'tx_001',
            'user_id': 2,
            'account_id': 2,
            'amount': 1000.0,
            'signature': 'signature_hash_1'
        },
        {
            'transaction_id': 'tx_002',
            'user_id': 3,
            'account_id': 3,
            'amount': 500.0,
            'signature': 'signature_hash_2'
        }
    ])

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('transactions')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
